# Generated by Django 3.0.8 on 2020-08-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200803_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_terms',
            field=models.BooleanField(default=False, help_text='Has this user accepted the terms & conditions?'),
        ),
        migrations.DeleteModel(
            name='ExamplePost',
        ),
    ]
