# Generated by Django 3.0.8 on 2020-08-01 00:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'post')},
        ),
        migrations.AlterIndexTogether(
            name='rating',
            index_together={('user', 'post')},
        ),
    ]
