# Generated by Django 3.0.2 on 2020-05-31 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comment_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_publick',
            new_name='is_public',
        ),
    ]
