# Generated by Django 3.0.6 on 2020-06-02 04:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_auto_20200531_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=140, unique=True)),
                ('text', models.TextField(default='')),
                ('public', models.BooleanField(default=True, help_text='If False, only followers will be able to see content.')),
                ('enrollment', models.IntegerField(choices=[('0', 'Self'), ('1Author', 'Author')], default='0')),
                ('followers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
