# Generated by Django 3.0.6 on 2020-06-02 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_channel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='post',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='post',
            name='read_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='width_field',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='custom_summary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(
                choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='posts.Tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='a', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.CharField(default='b', max_length=140, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='enrollment',
            field=models.IntegerField(
                choices=[(0, 'Self'), (1, 'Author')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
