# Generated by Django 3.0.6 on 2020-06-02 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200602_0453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
    ]
