# Generated by Django 3.0.6 on 2020-06-02 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200602_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='channel',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.Channel'),
            preserve_default=False,
        ),
    ]
