# Generated by Django 3.0.5 on 2020-05-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasdet',
            name='user_account',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comprasenc',
            name='user_account',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='user_account',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
